trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'AzureConnection'    # Your service connection name
  appName: 'java-poc-app'                 # Your Azure App Service name
  package: '$(System.DefaultWorkingDirectory)/target/*.jar'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'java-poc-app'
    package: '$(System.DefaultWorkingDirectory)/target/*.jar'
